In [1]:
!pip install /lakehouse/default/Files/fabric_sdk-0.1.0-py3-none-any.whl

StatementMeta(, 85f359bd-f58c-46c6-8c91-a2eb1be748b0, 3, Finished, Available, Finished)

Processing /lakehouse/default/Files/fabric_sdk-0.1.0-py3-none-any.whl
Requirement already satisfied: requests in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from fabric-sdk==0.1.0) (2.31.0)
Requirement already satisfied: semantic-link-sempy in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from fabric-sdk==0.1.0) (0.8.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from requests->fabric-sdk==0.1.0) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from requests->fabric-sdk==0.1.0) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from requests->fabric-sdk==0.1.0) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from requests->fabric-sdk==0.1.0) (2024.2.2)
Requirement already satisfied: clr-loader>=0.2.5 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy->fabric-sdk==0.1.0) (0.2.5)
Requirement already satisfied: graphviz>=0.20.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy->fabric-sdk==0.1.0) (0.20.1)
Requirement already satisfied: pyarrow>=12.0.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy->fabric-sdk==0.1.0) (14.0.2)
Requirement already satisfied: pythonnet>=3.0.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy->fabric-sdk==0.1.0) (3.0.1)
Requirement already satisfied: scikit-learn>=1.2.2 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy->fabric-sdk==0.1.0) (1.2.2)
Requirement already satisfied: setuptools>=68.2.2 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy->fabric-sdk==0.1.0) (68.2.2)
Requirement already satisfied: tqdm>=4.65.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy->fabric-sdk==0.1.0) (4.65.0)
Requirement already satisfied: cffi>=1.13 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from clr-loader>=0.2.5->semantic-link-sempy->fabric-sdk==0.1.0) (1.16.0)
Requirement already satisfied: numpy>=1.16.6 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from pyarrow>=12.0.1->semantic-link-sempy->fabric-sdk==0.1.0) (1.26.4)
Requirement already satisfied: scipy>=1.3.2 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from scikit-learn>=1.2.2->semantic-link-sempy->fabric-sdk==0.1.0) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from scikit-learn>=1.2.2->semantic-link-sempy->fabric-sdk==0.1.0) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from scikit-learn>=1.2.2->semantic-link-sempy->fabric-sdk==0.1.0) (2.2.0)
Requirement already satisfied: pycparser in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from cffi>=1.13->clr-loader>=0.2.5->semantic-link-sempy->fabric-sdk==0.1.0) (2.21)
Installing collected packages: fabric-sdk
Successfully installed fabric-sdk-0.1.0

In [2]:
from fabric_sdk.api import FabricAPIBase

# Create an instance and use the methods
fabric_api = FabricAPIBase()

StatementMeta(, 85f359bd-f58c-46c6-8c91-a2eb1be748b0, 4, Finished, Available, Finished)

In [3]:
fabric_api.GetAllLakehouses()

StatementMeta(, 85f359bd-f58c-46c6-8c91-a2eb1be748b0, 5, Finished, Available, Finished)

,Id,Display Name,Description,Type,Workspace Id
0,47cfcd75-d361-4de0-8ab1-1897d120ec4c,DataflowsStagingLakehouse,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857
1,62581562-429d-4f4f-a1cf-6247983d7742,sp_test_lakehouse,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857
2,72115710-5c4d-4f1b-ae5a-7f2cfa1c4844,genai,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857
3,382dab8f-918b-4f2c-8f9b-ffe07f0758bb,SentimentAnalysis,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857
4,bcec5c83-926d-44f2-bff3-ea82c668f76a,Sales_Lakehouse,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857
5,237003a4-b283-476d-8d5e-cc59e747c221,GenAI_DE,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857
6,36141d52-fb97-46f2-8388-64b668258e40,DEmoSample,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857
7,aadf020e-2f0d-48e1-b674-b955a30abb99,demo_01,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857
8,dc12f3ba-da6e-41fa-bb59-25198a2af0cc,hadi_demo,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857
9,7872424b-b632-4446-95b9-4deba26c6af2,test_FBSDK,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857

In [4]:
fabric_api.GetFabricWorkspaces()

StatementMeta(, 85f359bd-f58c-46c6-8c91-a2eb1be748b0, 6, Finished, Available, Finished)

,Id,Is Read Only,Is On Dedicated Capacity,Capacity Id,Default Dataset Storage Format,Type,Name,Git_status
0,252baade-39dd-4012-8312-35b9941f7d5f,False,True,7b9bd709-5866-4049-adb8-97388ed24120,Small,Workspace,Lab,NotConnected
1,ef8ecf7d-15c4-46cd-b786-125579ab4857,False,True,3d28dead-845c-4219-832d-ece0748f41f9,Small,Workspace,Fabric Demo-Dev,ConnectedAndInitialized

In [5]:
fabric_api.GetPowerBIWorkspaces()

StatementMeta(, 85f359bd-f58c-46c6-8c91-a2eb1be748b0, 7, Finished, Available, Finished)

,Id,Is Read Only,Is On Dedicated Capacity,Capacity Id,Default Dataset Storage Format,Type,Name,Git_status
2,fc9a40a2-9197-45ba-b4fa-b6e7dee85ce7,False,False,NaN,NaN,Workspace,test_GL,NotConnected
3,1e823130-5bd9-4f61-889e-1a27eb479aa0,False,True,78c4cbce-f584-4f12-a7a1-17d4852ecde4,Large,Workspace,Fabric-Demo,NotConnected
4,22b44eb2-f3be-442c-80d3-2f9b6bff0d28,False,True,95dcedc6-e90d-4bf0-a28a-8fb9603265fc,Small,Workspace,GAC-SSIS,NotConnected