In [ ]:
!pip install semantic-link-sempy

StatementMeta(, 96b2e551-98e8-4741-b4c4-1cb4e74be1a6, 3, Finished, Available, Finished)

Requirement already satisfied: semantic-link-sempy in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (0.8.0)
Requirement already satisfied: clr-loader>=0.2.5 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy) (0.2.5)
Requirement already satisfied: graphviz>=0.20.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy) (0.20.1)
Requirement already satisfied: pyarrow>=12.0.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy) (14.0.2)
Requirement already satisfied: pythonnet>=3.0.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy) (3.0.1)
Requirement already satisfied: scikit-learn>=1.2.2 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy) (1.2.2)
Requirement already satisfied: setuptools>=68.2.2 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy) (68.2.2)
Requirement already satisfied: tqdm>=4.65.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from semantic-link-sempy) (4.65.0)
Requirement already satisfied: cffi>=1.13 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from clr-loader>=0.2.5->semantic-link-sempy) (1.16.0)
Requirement already satisfied: numpy>=1.16.6 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from pyarrow>=12.0.1->semantic-link-sempy) (1.26.4)
Requirement already satisfied: scipy>=1.3.2 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from scikit-learn>=1.2.2->semantic-link-sempy) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from scikit-learn>=1.2.2->semantic-link-sempy) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from scikit-learn>=1.2.2->semantic-link-sempy) (2.2.0)
Requirement already satisfied: pycparser in /home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages (from cffi>=1.13->clr-loader>=0.2.5->semantic-link-sempy) (2.21)

In [ ]:
from sempy.fabric import list_workspaces ,list_items ,list_dataflows
from urllib.parse import urljoin
import requests
class FabricAPIBase:
    def __init__(self,  base_url=None):
        
        self.base_url = base_url or "https://api.fabric.microsoft.com/v1/"
        self.token = notebookutils.credentials.getToken('pbi')
    def make_request(self, method='GET', endpoint=None, params=None, data=None):
        
        
        url = urljoin(self.base_url, endpoint)
        headers = {
            'Authorization': f'Bearer {self.token}',
            'Content-Type': 'application/json'
        }

 
        response = requests.request(
            method,
            url,
            headers=headers,
            params=params,
            data=json.dumps(data) if data else None
        )
        response.raise_for_status()
        return response.json()
    def GetAllWorkspaces(self):
        self.workspaces = list_workspaces()
        self.workspaces['Git_status']=[ self.make_request('GET',f'workspaces/{id}/git/connection')['gitConnectionState'] for id in self.workspaces['Id']]
        return self.workspaces #dataframe
    def GetFabricWorkspaces(self):
        self.workspaces = list_workspaces()
        self.workspaces['Git_status']=[ self.make_request('GET',f'workspaces/{id}/git/connection')['gitConnectionState'] for id in self.workspaces['Id']]
        self.fabric_workspaces_IDs=[]
        for id in self.workspaces['Id']:
            if (('Lakehouse' in set(list_items(workspace=id)['Type'].values)) or 
                ('DataPipeline' in set(list_items(workspace=id)['Type'].values)) or 
                ('Warehouse' in set(list_items(workspace=id)['Type'].values)) or 
                ('Notebook' in set(list_items(workspace=id)['Type'].values)) or
                (list_dataflows(id).shape[0] > 0)):
                   self.fabric_workspaces_IDs.append(id)
        self.fabric_workspaces=self.workspaces[self.workspaces['Id'].isin(self.fabric_workspaces_IDs)]
        return self.fabric_workspaces
    def GetPowerBIWorkspaces(self):
        self.workspaces = list_workspaces()
        self.workspaces['Git_status']=[ self.make_request('GET',f'workspaces/{id}/git/connection')['gitConnectionState'] for id in self.workspaces['Id']]
        self.PowerBI_workspaces_IDs=[]
        for id in self.workspaces['Id']:
            if not (('Lakehouse' in set(list_items(workspace=id)['Type'].values)) or 
                ('DataPipeline' in set(list_items(workspace=id)['Type'].values)) or 
                ('Warehouse' in set(list_items(workspace=id)['Type'].values)) or 
                ('Notebook' in set(list_items(workspace=id)['Type'].values)) or
                (list_dataflows(id).shape[0] > 0)):
                   self.PowerBI_workspaces_IDs.append(id)
        self.PowerBI_workspaces=self.workspaces[self.workspaces['Id'].isin(self.PowerBI_workspaces_IDs)]
        return self.PowerBI_workspaces
    def GetAllWarehouses(self):
        return list_items('Warehouse')
    def GetAllLakehouses(self):
        return list_items('Lakehouse')
    def GetWarehouseByID(self,ID):
        self.warehouses=list_items('Warehouse')
        return self.warehouses[self.warehouses['Id']==ID]
    def GetWarehouseByName(self,Name):
        self.warehouses=list_items('Warehouse')
        return self.warehouses[self.warehouses['Display Name']==Name]
    def GetLakehouseByID(self,ID):
        self.Lakehouses=list_items('Lakehouse')
        return self.Lakehouses[self.Lakehouses['Id']==ID]
    def GetLakehouseByName(self,Name):
        self.Lakehouses=list_items('Lakehouse')
        return self.Lakehouses[self.Lakehouses['Display Name']==Name]

StatementMeta(, 96b2e551-98e8-4741-b4c4-1cb4e74be1a6, 9, Finished, Available, Finished)

In [ ]:
fabsdk=FabricAPIBase()

StatementMeta(, 96b2e551-98e8-4741-b4c4-1cb4e74be1a6, 10, Finished, Available, Finished)

In [ ]:
fabsdk.GetAllWorkspaces()

StatementMeta(, 96b2e551-98e8-4741-b4c4-1cb4e74be1a6, 11, Finished, Available, Finished)

,Id,Is Read Only,Is On Dedicated Capacity,Capacity Id,Default Dataset Storage Format,Type,Name,Git_status
0,252baade-39dd-4012-8312-35b9941f7d5f,False,True,7b9bd709-5866-4049-adb8-97388ed24120,Small,Workspace,Lab,NotConnected
1,ef8ecf7d-15c4-46cd-b786-125579ab4857,False,True,3d28dead-845c-4219-832d-ece0748f41f9,Small,Workspace,Fabric Demo-Dev,ConnectedAndInitialized
2,59e733b6-e5e6-40db-97dd-b9b2991a9146,False,True,78c4cbce-f584-4f12-a7a1-17d4852ecde4,Small,Workspace,Reports Showcase,NotConnected
3,fc9a40a2-9197-45ba-b4fa-b6e7dee85ce7,False,False,NaN,NaN,Workspace,test_GL,NotConnected

In [ ]:
fabsdk.GetFabricWorkspaces()

StatementMeta(, 96b2e551-98e8-4741-b4c4-1cb4e74be1a6, 12, Finished, Available, Finished)

,Id,Is Read Only,Is On Dedicated Capacity,Capacity Id,Default Dataset Storage Format,Type,Name,Git_status
0,252baade-39dd-4012-8312-35b9941f7d5f,False,True,7b9bd709-5866-4049-adb8-97388ed24120,Small,Workspace,Lab,NotConnected
1,ef8ecf7d-15c4-46cd-b786-125579ab4857,False,True,3d28dead-845c-4219-832d-ece0748f41f9,Small,Workspace,Fabric Demo-Dev,ConnectedAndInitialized
2,59e733b6-e5e6-40db-97dd-b9b2991a9146,False,True,78c4cbce-f584-4f12-a7a1-17d4852ecde4,Small,Workspace,Reports Showcase,NotConnected

In [ ]:
fabsdk.GetPowerBIWorkspaces()

StatementMeta(, 96b2e551-98e8-4741-b4c4-1cb4e74be1a6, 14, Finished, Available, Finished)

,Id,Is Read Only,Is On Dedicated Capacity,Capacity Id,Default Dataset Storage Format,Type,Name,Git_status
3,fc9a40a2-9197-45ba-b4fa-b6e7dee85ce7,False,False,NaN,NaN,Workspace,test_GL,NotConnected

In [ ]:
fabsdk.GetAllWarehouses()

StatementMeta(, 96b2e551-98e8-4741-b4c4-1cb4e74be1a6, 15, Finished, Available, Finished)

,Id,Display Name,Description,Type,Workspace Id
0,8e0c7924-c1ef-4671-a784-498375ba78b7,DataflowsStagingWarehouse,,Warehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857
1,57cf3b0c-7c6e-4f11-9dab-5b85a421cea7,sampleDataWarehouse,,Warehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857

In [ ]:
fabsdk.GetWarehouseByID('8e0c7924-c1ef-4671-a784-498375ba78b7')

StatementMeta(, 96b2e551-98e8-4741-b4c4-1cb4e74be1a6, 17, Finished, Available, Finished)

,Id,Display Name,Description,Type,Workspace Id
0,8e0c7924-c1ef-4671-a784-498375ba78b7,DataflowsStagingWarehouse,,Warehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857

In [ ]:
fabsdk.GetWarehouseByName('sampleDataWarehouse')

StatementMeta(, 96b2e551-98e8-4741-b4c4-1cb4e74be1a6, 18, Finished, Available, Finished)

,Id,Display Name,Description,Type,Workspace Id
1,57cf3b0c-7c6e-4f11-9dab-5b85a421cea7,sampleDataWarehouse,,Warehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857

In [ ]:
fabsdk.GetAllLakehouses()

StatementMeta(, 96b2e551-98e8-4741-b4c4-1cb4e74be1a6, 16, Finished, Available, Finished)

,Id,Display Name,Description,Type,Workspace Id
0,47cfcd75-d361-4de0-8ab1-1897d120ec4c,DataflowsStagingLakehouse,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857
1,62581562-429d-4f4f-a1cf-6247983d7742,sp_test_lakehouse,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857
2,72115710-5c4d-4f1b-ae5a-7f2cfa1c4844,genai,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857
3,382dab8f-918b-4f2c-8f9b-ffe07f0758bb,SentimentAnalysis,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857
4,bcec5c83-926d-44f2-bff3-ea82c668f76a,Sales_Lakehouse,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857
5,237003a4-b283-476d-8d5e-cc59e747c221,GenAI_DE,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857
6,36141d52-fb97-46f2-8388-64b668258e40,DEmoSample,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857
7,aadf020e-2f0d-48e1-b674-b955a30abb99,demo_01,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857

In [ ]:
fabsdk.GetLakehouseByID('bcec5c83-926d-44f2-bff3-ea82c668f76a')

StatementMeta(, 96b2e551-98e8-4741-b4c4-1cb4e74be1a6, 19, Finished, Available, Finished)

,Id,Display Name,Description,Type,Workspace Id
4,bcec5c83-926d-44f2-bff3-ea82c668f76a,Sales_Lakehouse,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857

In [ ]:
fabsdk.GetLakehouseByName('sp_test_lakehouse')

StatementMeta(, 96b2e551-98e8-4741-b4c4-1cb4e74be1a6, 20, Finished, Available, Finished)

,Id,Display Name,Description,Type,Workspace Id
1,62581562-429d-4f4f-a1cf-6247983d7742,sp_test_lakehouse,,Lakehouse,ef8ecf7d-15c4-46cd-b786-125579ab4857